### ISSUE TITLE
Support 2.5.0.27

### ISSUE THREAD

**Issue by bostrot** [ddvk/remarkable-splash#2]
It seems it does not work with the latest remarkable version on shutdown.

Maybe because it shows the "shutdown" dialog where it paints the whole screen black before actually shutting down?

**Comment by ddvk** [comment]
it should work with the rm2fb shim

**Comment by bostrot** [comment]
Isn't rm2fb just for the remarkable 2?

**Comment by ddvk** [comment]
ah, so you meant rm1, i ll have to test it then

**Comment by bostrot** [comment]
Is it actually just a replacement for the suspend splashscreen when the screen times out? Because I just found out that this works. (waiting 20 min for sleep)
Maybe that should be clarified in the readme then.

**Comment by ddvk** [comment]
yes, it was a replacement for remarkable-shutdown. when the device goes from suspend to shutdown.
